# Generated by Django 4.1.13 on 2024-05-12 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='formations/images/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=560)),
                ('department', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('enrollment_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FormationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='formations/images/')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='formations.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('department', models.CharField(max_length=255)),
                ('academic_level', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=255)),
                ('enrollment_date', models.DateField()),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formations.formation')),
            ],
            options={
                'unique_together': {('formation', 'email')},
            },
        ),
    ]
