# Generated by Django 4.1.13 on 2024-05-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formationimage',
            name='image',
            field=models.ImageField(upload_to='formations/images/formation_%Y/'),
        ),
    ]
