# Generated by Django 4.1.13 on 2024-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0002_alter_formationimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='doctor_specialty',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='formation',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='formation',
            name='place',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], max_length=255),
        ),
    ]
