# Generated by Django 4.1.13 on 2024-05-19 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0006_formation_places_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='map_url',
            field=models.URLField(blank=True, help_text='URL of the location on the map', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 0, 16, 5, 240544), null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='enrollment_deadline',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 0, 16, 5, 224947), null=True),
        ),
    ]
