# Generated by Django 4.1.13 on 2024-05-27 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0011_alter_enrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='map_url',
        ),
        migrations.AddField(
            model_name='formation',
            name='map_iframe',
            field=models.URLField(blank=True, help_text='iframe of the location on the map', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 18, 38, 40, 303171, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='enrollment_deadline',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 18, 38, 40, 303171, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
