# Generated by Django 4.1.13 on 2024-05-27 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0012_remove_formation_map_url_formation_map_iframe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 19, 8, 1, 419663, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='enrollment_deadline',
            field=models.DateField(default=datetime.datetime(2024, 5, 27, 19, 8, 1, 404041, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='map_iframe',
            field=models.TextField(blank=True, help_text='iframe of the location on the map', max_length=200, null=True),
        ),
    ]
