# Generated by Django 4.1.13 on 2024-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0015_alter_formation_map_iframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('privacy_policy', 'Privacy Policy'), ('terms_of_service', 'Terms of Service'), ('faq', 'FAQ')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Content of the site section')),
            ],
        ),
    ]
