# Generated by Django 4.1.13 on 2024-06-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0016_sitecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='address',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='doctor_specialty',
            new_name='specialty',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='academic_level',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='department',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Facebook', 'Facebook'), ('Website', 'Website')], default='Manual', editable=False, max_length=255),
        ),
    ]
