# Generated by Django 4.1.13 on 2024-06-01 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0017_rename_address_enrollment_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formation',
            old_name='enrollment_deadline',
            new_name='date',
        ),
    ]
