# Generated by Django 4.1.13 on 2024-06-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0018_rename_enrollment_deadline_formation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='session',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
