# Generated by Django 4.1.13 on 2024-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0021_alter_formation_price_alter_formation_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(max_length=100)),
                ('email_host', models.CharField(max_length=100)),
                ('email_port', models.PositiveIntegerField()),
                ('email_use_tls', models.BooleanField()),
                ('email_host_user', models.EmailField(max_length=254)),
                ('email_host_password', models.CharField(max_length=100)),
            ],
        ),
    ]
