# Generated by Django 4.1.13 on 2024-06-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0024_sitesettings_setting_name_sitesettings_setting_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='instructor',
            field=models.CharField(blank=True, default='', max_length=560),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='setting_name',
            field=models.CharField(choices=[('EMAIL_RECEIVER', 'EMAIL RECEIVER'), ('EMAIL_HOST_PASSWORD', 'EMAIL HOST PASSWORD'), ('EMAIL_HOST_USER', 'EMAIL HOST USER')], max_length=100, unique=True),
        ),
    ]
