# Generated by Django 4.1.13 on 2024-06-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0026_customgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomGroup',
        ),
    ]
